import 'dotenv/config';
import { AppDataSource } from '../config/data-source';
import { Country } from '../entities/Country';

export const preloadCountries = async () => {
   try {
      // Create some countries to insert
      const countries: Partial<Country>[] = [
         { flagCode: 'AF', name: 'Afghanistan', id: 4 },
         { flagCode: 'AL', name: 'Albania', id: 8 },
         { flagCode: 'DZ', name: 'Algeria', id: 12 },
         { flagCode: 'AS', name: 'American Samoa', id: 16 },
         { flagCode: 'AD', name: 'Andorra', id: 20 },
         { flagCode: 'AO', name: 'Angola', id: 24 },
         { flagCode: 'AI', name: 'Anguilla', id: 660 },
         { flagCode: 'AQ', name: 'Antarctica', id: 10 },
         { flagCode: 'AG', name: 'Antigua and Barbuda', id: 28 },
         { flagCode: 'AR', name: 'Argentina', id: 32 },
         { flagCode: 'AM', name: 'Armenia', id: 51 },
         { flagCode: 'AW', name: 'Aruba', id: 533 },
         { flagCode: 'AU', name: 'Australia', id: 36 },
         { flagCode: 'AT', name: 'Austria', id: 40 },
         { flagCode: 'AZ', name: 'Azerbaijan', id: 31 },
         { flagCode: 'BS', name: 'Bahamas (the)', id: 44 },
         { flagCode: 'BH', name: 'Bahrain', id: 48 },
         { flagCode: 'BD', name: 'Bangladesh', id: 50 },
         { flagCode: 'BB', name: 'Barbados', id: 52 },
         { flagCode: 'BY', name: 'Belarus', id: 112 },
         { flagCode: 'BE', name: 'Belgium', id: 56 },
         { flagCode: 'BZ', name: 'Belize', id: 84 },
         { flagCode: 'BJ', name: 'Benin', id: 204 },
         { flagCode: 'BM', name: 'Bermuda', id: 60 },
         { flagCode: 'BT', name: 'Bhutan', id: 64 },
         {
            flagCode: 'BO',
            name: 'Bolivia (Plurinational State of)',
            id: 68,
         },
         {
            flagCode: 'BQ',
            name: 'Bonaire, Sint Eustatius and Saba',
            id: 535,
         },
         { flagCode: 'BA', name: 'Bosnia and Herzegovina', id: 70 },
         { flagCode: 'BW', name: 'Botswana', id: 72 },
         { flagCode: 'BV', name: 'Bouvet Island', id: 74 },
         { flagCode: 'BR', name: 'Brazil', id: 76 },
         {
            flagCode: 'IO',
            name: 'British Indian Ocean Territory (the)',
            id: 86,
         },
         { flagCode: 'BN', name: 'Brunei Darussalam', id: 96 },
         { flagCode: 'BG', name: 'Bulgaria', id: 1 },
         { flagCode: 'BF', name: 'Burkina Faso', id: 854 },
         { flagCode: 'BI', name: 'Burundi', id: 108 },
         { flagCode: 'CV', name: 'Cabo Verde', id: 132 },
         { flagCode: 'KH', name: 'Cambodia', id: 116 },
         { flagCode: 'CM', name: 'Cameroon', id: 120 },
         { flagCode: 'CA', name: 'Canada', id: 124 },
         { flagCode: 'KY', name: 'Cayman Islands (the)', id: 136 },
         {
            flagCode: 'CF',
            name: 'Central African Republic (the)',
            id: 140,
         },
         { flagCode: 'TD', name: 'Chad', id: 148 },
         { flagCode: 'CL', name: 'Chile', id: 152 },
         { flagCode: 'CN', name: 'China', id: 156 },
         { flagCode: 'CX', name: 'Christmas Island', id: 162 },
         {
            flagCode: 'CC',
            name: 'Cocos (Keeling) Islands (the)',
            id: 166,
         },
         { flagCode: 'CO', name: 'Colombia', id: 170 },
         { flagCode: 'KM', name: 'Comoros (the)', id: 174 },
         {
            flagCode: 'CD',
            name: 'Congo (the Democratic Republic of the)',
            id: 180,
         },
         { flagCode: 'CG', name: 'Congo (the)', id: 178 },
         { flagCode: 'CK', name: 'Cook Islands (the)', id: 184 },
         { flagCode: 'CR', name: 'Costa Rica', id: 188 },
         { flagCode: 'HR', name: 'Croatia', id: 191 },
         { flagCode: 'CU', name: 'Cuba', id: 192 },
         { flagCode: 'CW', name: 'Curaçao', id: 531 },
         { flagCode: 'CY', name: 'Cyprus', id: 196 },
         { flagCode: 'CZ', name: 'Czechia', id: 203 },
         { flagCode: 'CI', name: "Côte d'Ivoire", id: 384 },
         { flagCode: 'DK', name: 'Denmark', id: 208 },
         { flagCode: 'DJ', name: 'Djibouti', id: 262 },
         { flagCode: 'DM', name: 'Dominica', id: 212 },
         {
            flagCode: 'DO',
            name: 'Dominican Republic (the)',
            id: 214,
         },
         { flagCode: 'EC', name: 'Ecuador', id: 218 },
         { flagCode: 'EG', name: 'Egypt', id: 818 },
         { flagCode: 'SV', name: 'El Salvador', id: 222 },
         { flagCode: 'GQ', name: 'Equatorial Guinea', id: 226 },
         { flagCode: 'ER', name: 'Eritrea', id: 232 },
         { flagCode: 'EE', name: 'Estonia', id: 233 },
         { flagCode: 'SZ', name: 'Eswatini', id: 748 },
         { flagCode: 'ET', name: 'Ethiopia', id: 231 },
         {
            flagCode: 'FK',
            name: 'Falkland Islands (the) [Malvinas]',
            id: 238,
         },
         { flagCode: 'FO', name: 'Faroe Islands (the)', id: 234 },
         { flagCode: 'FJ', name: 'Fiji', id: 242 },
         { flagCode: 'FI', name: 'Finland', id: 246 },
         { flagCode: 'FR', name: 'France', id: 250 },
         { flagCode: 'GF', name: 'French Guiana', id: 254 },
         { flagCode: 'PF', name: 'French Polynesia', id: 258 },
         {
            flagCode: 'TF',
            name: 'French Southern Territories (the)',
            id: 260,
         },
         { flagCode: 'GA', name: 'Gabon', id: 266 },
         { flagCode: 'GM', name: 'Gambia (the)', id: 270 },
         { flagCode: 'GE', name: 'Georgia', id: 268 },
         { flagCode: 'DE', name: 'Germany', id: 276 },
         { flagCode: 'GH', name: 'Ghana', id: 288 },
         { flagCode: 'GI', name: 'Gibraltar', id: 292 },
         { flagCode: 'GR', name: 'Greece', id: 3 },
         { flagCode: 'GL', name: 'Greenland', id: 304 },
         { flagCode: 'GD', name: 'Grenada', id: 308 },
         { flagCode: 'GP', name: 'Guadeloupe', id: 312 },
         { flagCode: 'GU', name: 'Guam', id: 316 },
         { flagCode: 'GT', name: 'Guatemala', id: 320 },
         { flagCode: 'GG', name: 'Guernsey', id: 831 },
         { flagCode: 'GN', name: 'Guinea', id: 324 },
         { flagCode: 'GW', name: 'Guinea-Bissau', id: 624 },
         { flagCode: 'GY', name: 'Guyana', id: 328 },
         { flagCode: 'HT', name: 'Haiti', id: 332 },
         {
            flagCode: 'HM',
            name: 'Heard Island and McDonald Islands',
            id: 334,
         },
         { flagCode: 'VA', name: 'Holy See (the)', id: 336 },
         { flagCode: 'HN', name: 'Honduras', id: 340 },
         { flagCode: 'HK', name: 'Hong Kong', id: 344 },
         { flagCode: 'HU', name: 'Hungary', id: 348 },
         { flagCode: 'IS', name: 'Iceland', id: 352 },
         { flagCode: 'IN', name: 'India', id: 356 },
         { flagCode: 'ID', name: 'Indonesia', id: 360 },
         {
            flagCode: 'IR',
            name: 'Iran (Islamic Republic of)',
            id: 364,
         },
         { flagCode: 'IQ', name: 'Iraq', id: 368 },
         { flagCode: 'IE', name: 'Ireland', id: 372 },
         { flagCode: 'IM', name: 'Isle of Man', id: 833 },
         { flagCode: 'IL', name: 'Israel', id: 376 },
         { flagCode: 'IT', name: 'Italy', id: 380 },
         { flagCode: 'JM', name: 'Jamaica', id: 388 },
         { flagCode: 'JP', name: 'Japan', id: 392 },
         { flagCode: 'JE', name: 'Jersey', id: 832 },
         { flagCode: 'JO', name: 'Jordan', id: 4 },
         { flagCode: 'KZ', name: 'Kazakhstan', id: 398 },
         { flagCode: 'KE', name: 'Kenya', id: 404 },
         { flagCode: 'KI', name: 'Kiribati', id: 296 },
         {
            flagCode: 'KP',
            name: "Korea (the Democratic People's Republic of)",
            id: 408,
         },
         { flagCode: 'KR', name: 'Korea (the Republic of)', id: 410 },
         { flagCode: 'KW', name: 'Kuwait', id: 414 },
         { flagCode: 'KG', name: 'Kyrgyzstan', id: 417 },
         {
            flagCode: 'LA',
            name: "Lao People's Democratic Republic (the)",
            id: 418,
         },
         { flagCode: 'LV', name: 'Latvia', id: 428 },
         { flagCode: 'LB', name: 'Lebanon', id: 422 },
         { flagCode: 'LS', name: 'Lesotho', id: 426 },
         { flagCode: 'LR', name: 'Liberia', id: 430 },
         { flagCode: 'LY', name: 'Libya', id: 434 },
         { flagCode: 'LI', name: 'Liechtenstein', id: 438 },
         { flagCode: 'LT', name: 'Lithuania', id: 440 },
         { flagCode: 'LU', name: 'Luxembourg', id: 442 },
         { flagCode: 'MO', name: 'Macao', id: 446 },
         { flagCode: 'MG', name: 'Madagascar', id: 450 },
         { flagCode: 'MW', name: 'Malawi', id: 454 },
         { flagCode: 'MY', name: 'Malaysia', id: 458 },
         { flagCode: 'MV', name: 'Maldives', id: 462 },
         { flagCode: 'ML', name: 'Mali', id: 466 },
         { flagCode: 'MT', name: 'Malta', id: 470 },
         { flagCode: 'MH', name: 'Marshall Islands (the)', id: 584 },
         { flagCode: 'MQ', name: 'Martinique', id: 474 },
         { flagCode: 'MR', name: 'Mauritania', id: 478 },
         { flagCode: 'MU', name: 'Mauritius', id: 480 },
         { flagCode: 'YT', name: 'Mayotte', id: 175 },
         { flagCode: 'MX', name: 'Mexico', id: 484 },
         {
            flagCode: 'FM',
            name: 'Micronesia (Federated States of)',
            id: 583,
         },
         {
            flagCode: 'MD',
            name: 'Moldova (the Republic of)',
            id: 498,
         },
         { flagCode: 'MC', name: 'Monaco', id: 492 },
         { flagCode: 'MN', name: 'Mongolia', id: 496 },
         { flagCode: 'ME', name: 'Montenegro', id: 499 },
         { flagCode: 'MS', name: 'Montserrat', id: 5 },
         { flagCode: 'MA', name: 'Morocco', id: 504 },
         { flagCode: 'MZ', name: 'Mozambique', id: 508 },
         { flagCode: 'MM', name: 'Myanmar', id: 104 },
         { flagCode: 'NA', name: 'Namibia', id: 516 },
         { flagCode: 'NR', name: 'Nauru', id: 520 },
         { flagCode: 'NP', name: 'Nepal', id: 524 },
         { flagCode: 'NL', name: 'Netherlands (the)', id: 528 },
         { flagCode: 'NC', name: 'New Caledonia', id: 540 },
         { flagCode: 'NZ', name: 'New Zealand', id: 554 },
         { flagCode: 'NI', name: 'Nicaragua', id: 558 },
         { flagCode: 'NE', name: 'Niger (the)', id: 562 },
         { flagCode: 'NG', name: 'Nigeria', id: 566 },
         { flagCode: 'NU', name: 'Niue', id: 570 },
         { flagCode: 'NF', name: 'Norfolk Island', id: 574 },
         {
            flagCode: 'MP',
            name: 'Northern Mariana Islands (the)',
            id: 580,
         },
         { flagCode: 'NO', name: 'Norway', id: 578 },
         { flagCode: 'OM', name: 'Oman', id: 512 },
         { flagCode: 'PK', name: 'Pakistan', id: 586 },
         { flagCode: 'PW', name: 'Palau', id: 585 },
         { flagCode: 'PS', name: 'Palestine, State of', id: 275 },
         { flagCode: 'PA', name: 'Panama', id: 591 },
         { flagCode: 'PG', name: 'Papua New Guinea', id: 598 },
         { flagCode: 'PY', name: 'Paraguay', id: 6 },
         { flagCode: 'PE', name: 'Peru', id: 604 },
         { flagCode: 'PH', name: 'Philippines (the)', id: 608 },
         { flagCode: 'PN', name: 'Pitcairn', id: 612 },
         { flagCode: 'PL', name: 'Poland', id: 616 },
         { flagCode: 'PT', name: 'Portugal', id: 620 },
         { flagCode: 'PR', name: 'Puerto Rico', id: 630 },
         { flagCode: 'QA', name: 'Qatar', id: 634 },
         {
            flagCode: 'MK',
            name: 'Republic of North Macedonia',
            id: 807,
         },
         { flagCode: 'RO', name: 'Romania', id: 642 },
         {
            flagCode: 'RU',
            name: 'Russian Federation (the)',
            id: 643,
         },
         { flagCode: 'RW', name: 'Rwanda', id: 646 },
         { flagCode: 'RE', name: 'Réunion', id: 638 },
         { flagCode: 'BL', name: 'Saint Barthélemy', id: 652 },
         {
            flagCode: 'SH',
            name: 'Saint Helena, Ascension and Tristan da Cunha',
            id: 654,
         },
         { flagCode: 'KN', name: 'Saint Kitts and Nevis', id: 659 },
         { flagCode: 'LC', name: 'Saint Lucia', id: 662 },
         {
            flagCode: 'MF',
            name: 'Saint Martin (French part)',
            id: 663,
         },
         {
            flagCode: 'PM',
            name: 'Saint Pierre and Miquelon',
            id: 666,
         },
         {
            flagCode: 'VC',
            name: 'Saint Vincent and the Grenadines',
            id: 670,
         },
         { flagCode: 'WS', name: 'Samoa', id: 882 },
         { flagCode: 'SM', name: 'San Marino', id: 674 },
         { flagCode: 'ST', name: 'Sao Tome and Principe', id: 678 },
         { flagCode: 'SA', name: 'Saudi Arabia', id: 682 },
         { flagCode: 'SN', name: 'Senegal', id: 686 },
         { flagCode: 'RS', name: 'Serbia', id: 688 },
         { flagCode: 'SC', name: 'Seychelles', id: 690 },
         { flagCode: 'SL', name: 'Sierra Leone', id: 694 },
         { flagCode: 'SG', name: 'Singapore', id: 702 },
         {
            flagCode: 'SX',
            name: 'Sint Maarten (Dutch part)',
            id: 534,
         },
         { flagCode: 'SK', name: 'Slovakia', id: 703 },
         { flagCode: 'SI', name: 'Slovenia', id: 705 },
         { flagCode: 'SB', name: 'Solomon Islands', id: 90 },
         { flagCode: 'SO', name: 'Somalia', id: 706 },
         { flagCode: 'ZA', name: 'South Africa', id: 710 },
         {
            flagCode: 'GS',
            name: 'South Georgia and the South Sandwich Islands',
            id: 239,
         },
         { flagCode: 'SS', name: 'South Sudan', id: 728 },
         { flagCode: 'ES', name: 'Spain', id: 724 },
         { flagCode: 'LK', name: 'Sri Lanka', id: 144 },
         { flagCode: 'SD', name: 'Sudan (the)', id: 729 },
         { flagCode: 'SR', name: 'Suriname', id: 740 },
         { flagCode: 'SJ', name: 'Svalbard and Jan Mayen', id: 744 },
         { flagCode: 'SE', name: 'Sweden', id: 752 },
         { flagCode: 'CH', name: 'Switzerland', id: 756 },
         { flagCode: 'SY', name: 'Syrian Arab Republic', id: 760 },
         { flagCode: 'TW', name: 'Taiwan', id: 158 },
         { flagCode: 'TJ', name: 'Tajikistan', id: 762 },
         {
            flagCode: 'TZ',
            name: 'Tanzania, United Republic of',
            id: 834,
         },
         { flagCode: 'TH', name: 'Thailand', id: 764 },
         { flagCode: 'TL', name: 'Timor-Leste', id: 626 },
         { flagCode: 'TG', name: 'Togo', id: 768 },
         { flagCode: 'TK', name: 'Tokelau', id: 772 },
         { flagCode: 'TO', name: 'Tonga', id: 776 },
         { flagCode: 'TT', name: 'Trinidad and Tobago', id: 780 },
         { flagCode: 'TN', name: 'Tunisia', id: 788 },
         { flagCode: 'TR', name: 'Turkey', id: 792 },
         { flagCode: 'TM', name: 'Turkmenistan', id: 795 },
         {
            flagCode: 'TC',
            name: 'Turks and Caicos Islands (the)',
            id: 796,
         },
         { flagCode: 'TV', name: 'Tuvalu', id: 798 },
         { flagCode: 'UG', name: 'Uganda', id: 8 },
         { flagCode: 'UA', name: 'Ukraine', id: 804 },
         {
            flagCode: 'AE',
            name: 'United Arab Emirates (the)',
            id: 784,
         },
         {
            flagCode: 'GB',
            name: 'United Kingdom of Great Britain and Northern Ireland (the)',
            id: 826,
         },
         {
            flagCode: 'UM',
            name: 'United States Minor Outlying Islands (the)',
            id: 581,
         },
         {
            flagCode: 'US',
            name: 'United States of America (the)',
            id: 840,
         },
         { flagCode: 'UY', name: 'Uruguay', id: 858 },
         { flagCode: 'UZ', name: 'Uzbekistan', id: 860 },
         { flagCode: 'VU', name: 'Vanuatu', id: 548 },
         {
            flagCode: 'VE',
            name: 'Venezuela (Bolivarian Republic of)',
            id: 862,
         },
         { flagCode: 'VN', name: 'Viet Nam', id: 704 },
         {
            flagCode: 'VG',
            name: 'Virgin Islands (British)',
            id: 92,
         },
         { flagCode: 'VI', name: 'Virgin Islands (U.S.)', id: 850 },
         { flagCode: 'WF', name: 'Wallis and Futuna', id: 876 },
         { flagCode: 'EH', name: 'Western Sahara', id: 732 },
         { flagCode: 'YE', name: 'Yemen', id: 887 },
         { flagCode: 'ZM', name: 'Zambia', id: 894 },
         { flagCode: 'ZW', name: 'Zimbabwe', id: 716 },
         { flagCode: 'AX', name: 'Åland Islands', id: 248 },
      ];

      // Insert the countries into the database
      const countryRepository = AppDataSource.getRepository(Country);

      const insertedCountries = countryRepository.find();

      if ((await insertedCountries).length > 0) {
         console.log('Countries already inserted!');
      } else {
         await countryRepository.save(countries);
         console.log('Countries preloaded successfully!');
      }
   } catch (error) {
      console.error('Error preloading countries:', error);
   }
};
